# Example Docker setup for Asian Weather App
version: '3'

services:
  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: weather-app-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - ORIGIN=${CLIENT_URL}
    networks:
      - app-network

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${API_URL}
    container_name: weather-app-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge